### ISSUE TITLE
Link quebrado

### ISSUE THREAD

**Issue by carlospcastro** [ebwang/ebwang#1]
Ola Eduardo tudo bem?
Achei muito legal o teu readme file, porem alguns links estao quebrados:

I’m looking to collaborate on [sheets-database](https://github.com/ebang/sheets-database)
📝   Checkout my [resume](https://drive.google.com/)

Parabens pelo otimo trabalho.
Ate mais

**Comment by ebwang** [comment]
Vlw meu amigo! Vou atualizar assim q possivel.

**Comment by ebwang** [comment]
Resolvido. Gostaria que vc visse se temos mais problemas na minha pagina de perfil. Obrigado

**Comment by carlospcastro** [comment]
LGTM
